---
id: rptscene-api
name: RPTScene
description: "RPTScene (RPTorrents) is a Private Torrent Tracker for MOVIES / TV / GENERAL"
language: en-US
type: private
encoding: UTF-8
links:
  - https://rptscene.xyz/

caps:
  categorymappings:
    - {id: 1, cat: Movies/HD, desc: "Movies HD"}
    - {id: 2, cat: Movies/HD, desc: "Movies HD-RO"}
    - {id: 3, cat: Movies/HD, desc: "Movie Pack HD-RO"}
    - {id: 5, cat: Movies/BluRay, desc: "Movies Bluray"}
    - {id: 6, cat: Movies/BluRay, desc: "Movies Bluray-RO"}
    - {id: 7, cat: Movies/UHD, desc: "Movies 4K"}
    - {id: 8, cat: Movies/UHD, desc: "Movies 4K-RO"}
    - {id: 9, cat: TV, desc: "TV"}
    - {id: 10, cat: TV, desc: "TV RO"}
    - {id: 11, cat: TV, desc: "TV Pack-RO"}
    - {id: 12, cat: Audio/MP3, desc: "Music Mp3"}
    - {id: 13, cat: Audio/Lossless, desc: "Music Flac"}
    - {id: 14, cat: Audio/Video, desc: "Music Video"}
    - {id: 15, cat: Movies, desc: "Movies Cartoons"}
    - {id: 16, cat: Movies, desc: "Movies Cartoons-RO"}
    - {id: 17, cat: Console, desc: "Game"}
    - {id: 18, cat: PC/0day, desc: "Application Win"}
    - {id: 19, cat: PC/Mac, desc: "Application Mac"}
    - {id: 20, cat: XXX, desc: "Movies XXX"}
    - {id: 21, cat: Books, desc: "E-Book"}
    - {id: 22, cat: TV/Anime, desc: "Anime"}
    - {id: 23, cat: PC, desc: "Linux"}
    - {id: 24, cat: PC/Mobile-Other, desc: "Mobile"}
    - {id: 51, cat: TV/Documentary, desc: "Documentary"}
    - {id: 52, cat: TV, desc: "TV Cartoons-Ro"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid, tvdbid, tmdbid]
    movie-search: [q, imdbid, tmdbid]
    music-search: [q]
    book-search: [q]

settings:
  - name: apikey
    type: text
    label: APIKey
  - name: info_key
    type: info
    label: About your API key
    default: "Find or Generate a new API Token by accessing your <a href=\"https://rptscene.xyz/\" target=\"_blank\">RPTorrents</a> account <i>My Settings</i> page and clicking on the <b>API Key</b> tab."
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: created_at
    options:
      created_at: created
      seeders: seeders
      size: size
      name: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc

login:
  path: /api/torrents
  method: get
  error:
    - selector: a[href*="/login"]
      message:
        text: "The API key was not accepted by {{ .Config.sitelink }}."

search:
  paths:
    # https://github.com/HDInnovations/UNIT3D-Community-Edition/wiki/Torrent-API-(UNIT3D-v7.0.0)
    # https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/app/Http/Controllers/API/TorrentController.php#L349
    - path: "/api/torrents/filter"
      response:
        type: json

  headers:
    Authorization: ["Bearer {{ .Config.apikey }}"]

  inputs:
  # if we have an id based search, add Season and Episode as query in name for UNIT3D < v6.  Else pass S/E Params for UNIT3D >= v6
    $raw: "{{ range .Categories }}&categories[]={{.}}{{end}}"
    name: "{{ .Keywords }}"
    seasonNumber: "{{ .Query.Season }}"
    episodeNumber: "{{ .Query.Ep }}"
    imdbId: "{{ .Query.IMDBIDShort }}"
    tmdbId: "{{ .Query.TMDBID }}"
    tvdbId: "{{ .Query.TVDBID }}"
    "free[]": "{{ if .Config.freeleech }}100{{ else }}{{ end }}"
    sortField: "{{ .Config.sort }}"
    sortDirection: "{{ .Config.type }}"
    perPage: 100

  keywordsfilters:
    - name: re_replace
      args: ["\\.", " "]

  rows:
    selector: data
    attribute: attributes

  fields:
    category:
      selector: category_id
    title:
      selector: name
    details:
      selector: details_link
    download:
      selector: download_link
    infohash:
      selector: info_hash
    poster:
      selector: meta.poster
      filters:
        - name: replace
          args: ["https://via.placeholder.com/90x135", ""]
    imdbid:
      selector: imdb_id
    tmdbid:
      selector: tmdb_id
    tvdbid:
      selector: tvdb_id
    genre:
      selector: meta.genres
      filters:
        - name: re_replace
          args: ["(?i)(Science Fiction)", "Science_Fiction"]
        - name: re_replace
          args: ["(?i)(TV Movie)", "TV_Movie"]
        - name: replace
          args: [" & ", "_&_"]
    description:
      text: "{{ .Result.genre }}"
    files:
      selector: num_file
    seeders:
      selector: seeders
    leechers:
      selector: leechers
    grabs:
      selector: times_completed
    date:
      # "created_at": "2021-10-18T00:34:50.000000Z" is returned by Newtonsoft.Json.Linq as 18/10/2021 00:34:50
      selector: created_at
      filters:
        - name: append
          args: " +00:00" # GMT
        - name: dateparse
          args: "MM/dd/yyyy HH:mm:ss zzz"
    size:
      selector: size
    downloadvolumefactor:
      # api returns 0%, 25%, 50%, 75%, 100%
      selector: freeleech
      case:
        0%: 1 # not free
        25%: 0.75
        50%: 0.5
        75%: 0.25
        100%: 0 # freeleech
        "*": 0 # catch errors
    uploadvolumefactor:
      # api returns False, True
      selector: double_upload
      case:
        False: 1 # normal
        True: 2 # double
# global MR is 0.4 but torrents must be seeded for 7 days regardless of ratio
#    minimumratio:
#      text: 0.4
    minimumseedtime:
      # 7 day (as seconds = 7 x 24 x 60 x 60)
      text: 604800
# json UNIT3D 7.1.3
